# Generated by Django 2.0.8 on 2018-08-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmapp', '0003_queuedfile_target_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('mtime', models.IntegerField()),
            ],
        ),
    ]
